# Generated by Django 3.2.20 on 2023-08-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_profile_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_student',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NotificationSchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_school')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackSchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_school')),
            ],
        ),
    ]
