# Generated by Django 3.2.20 on 2023-09-22 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^(\\+\\d{1,2}\\s?)?(\\d{1,4}[-\\s]?)?\\d{1,10}$'), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
