# Generated by Django 3.2.20 on 2023-09-22 15:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_enquiry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=50, validators=[users.models.validate_mobile_number]),
        ),
    ]
