# Generated by Django 3.2.20 on 2023-10-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_enquiry_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_student',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
    ]
