# Generated by Django 3.2.20 on 2023-10-04 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_profile_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^\\+?[0-9]+$')]),
        ),
    ]
