# Generated by Django 3.2.20 on 2023-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_student',
            name='section',
            field=models.CharField(default='', max_length=50),
        ),
    ]
