# Generated by Django 3.2.20 on 2024-03-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_profile_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroplanner', models.FileField(upload_to='')),
                ('microplanner', models.FileField(upload_to='')),
                ('content', models.URLField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_teacher')),
            ],
        ),
    ]
