# Generated by Django 3.2.20 on 2024-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_microplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplanner',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='microplanner',
            name='month',
            field=models.CharField(default='', max_length=100),
        ),
    ]
