# Generated by Django 3.2.20 on 2024-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_advocacyvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacyvisit',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advocacyvisit',
            name='school',
            field=models.CharField(choices=[('Sparsh Global SChool,Greater Noida', 'Sparsh Global SChool,Greater Noida'), ('JP International School, Greater Noida', 'JP International School, Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun')], default=None, max_length=100),
        ),
    ]
