# Generated by Django 3.2.20 on 2024-05-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_advocacyvisit_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macroplanner',
            name='month',
        ),
        migrations.AddField(
            model_name='macroplanner',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_school'),
        ),
        migrations.AddField(
            model_name='microplanner',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_school'),
        ),
    ]
