# Generated by Django 3.2.20 on 2024-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_competition_guestsession_innovationclub_kreativityshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('Sparsh Global School,Greater Noida', 'Sparsh Global SChool,Greater Noida'), ('JP International School, Greater Noida', 'JP International School, Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
