# Generated by Django 3.2.20 on 2024-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_schoolgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacyvisit',
            name='gallery',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advocacyvisit',
            name='verified_by',
            field=models.BooleanField(default=False),
        ),
    ]
