# Generated by Django 3.2.20 on 2024-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20240607_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationclub',
            name='month',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='kit_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='innovationclub',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='kits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='school',
            field=models.CharField(choices=[('Sparsh Global School,Greater Noida', 'Sparsh Global School,Greater Noida'), ('JP International School, Greater Noida', 'JP International School, Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun')], max_length=100),
        ),
    ]
