# Generated by Django 3.2.20 on 2024-07-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20240706_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student'),
        ),
        migrations.AddField(
            model_name='innovationclub',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
