# Generated by Django 3.2.20 on 2024-07-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20240711_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationclub',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student'),
        ),
    ]
