# Generated by Django 3.2.20 on 2024-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_innovationclub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bill_of_materials',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
