# Generated by Django 5.1 on 2024-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_useractivity1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': "School's Logo"},
        ),
        migrations.AlterModelOptions(
            name='schoolgallery',
            options={'verbose_name_plural': "School's Galleries"},
        ),
        migrations.AlterModelOptions(
            name='studentinnovativeproject',
            options={'verbose_name': 'Student Innovative Project'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_parent',
            options={'verbose_name': 'User Profile Parent'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_principal',
            options={'verbose_name': 'User Profile Principal'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_school',
            options={'verbose_name': 'User Profile School'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_student',
            options={'verbose_name': 'User Profile Student'},
        ),
        migrations.AlterModelOptions(
            name='user_profile_teacher',
            options={'verbose_name': 'User Profile Teacher'},
        ),
        migrations.AlterModelOptions(
            name='useractivity1',
            options={'verbose_name': 'user Acess Report', 'verbose_name_plural': 'user Acess Reports'},
        ),
        migrations.AlterModelOptions(
            name='userloginactivity',
            options={'verbose_name': 'user Login Activity', 'verbose_name_plural': 'user Login Activities'},
        ),
    ]
