# Generated by Django 5.1 on 2024-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_quiz_grade'),
        ('curriculum', '0018_lesson_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='schools',
            field=models.ManyToManyField(to='curriculum.school'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='date_attempted',
            field=models.DateTimeField(auto_now_add=True, null=True,blank=True),
        ),
    ]
