# Generated by Django 5.1 on 2024-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_quiz_date_quiz_end_date_quiz_schools_quiz_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
