# Generated by Django 5.1 on 2024-09-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_quiz_date'),
        ('assessment', '0005_alter_quiz_end_date_alter_quiz_start_date'),
    ]

    operations = [
    ]
