# Generated by Django 5.1 on 2024-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_quiz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True,null=True),
        ),
    ]
