# Generated by Django 3.2.20 on 2023-08-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230817_1626'),
        ('curriculum', '0009_auto_20230810_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topicwise_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculum.lesson')),
            ],
        ),
    ]
