# Generated by Django 3.2.20 on 2023-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_lesson_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video1',
            field=models.URLField(default='', max_length=300, verbose_name='Videos'),
        ),
    ]
