# Generated by Django 3.2.20 on 2024-01-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_lesson_video1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assessment',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video1',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Videos'),
        ),
    ]
