# Generated by Django 3.2.20 on 2024-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_auto_20240131_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='display_on_frontend',
            field=models.BooleanField(default=True, verbose_name='Display on Frontend'),
        ),
        migrations.AddField(
            model_name='subject',
            name='display_on_frontend',
            field=models.BooleanField(default=True, verbose_name='Display on Frontend'),
        ),
    ]
