# Generated by Django 3.2.20 on 2024-05-03 11:26

import curriculum.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_auto_20240502_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
            ],
            options={
                'verbose_name_plural': '2. Teacher Subjects',
            },
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Videos')),
                ('assessment', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Assessment')),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_lessons', to='curriculum.teachersubject')),
            ],
            options={
                'verbose_name_plural': '3. Teacher Lessons',
                'ordering': ['position'],
            },
        ),
    ]
