# Generated by Django 3.2.20 on 2024-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_teacherlesson_teachersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Schools',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='schools',
            field=models.ManyToManyField(to='curriculum.School'),
        ),
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(to='curriculum.School'),
        ),
    ]
