# Generated by Django 5.1 on 2024-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20240822_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Learning Aids'),
        ),
    ]
